typography_spectrum: 0.1441691005602479
color:
  brandStrength: 0.4215458258986473
  lightness: 0.39335649088025093
  saturation: 0.33048087428323925
  rhythmicContrast: 0.5698261151555926
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.4575715004466474
author:
  name: Mark Palmer
  email: mpalmer@peoplewerx.com
  url: www.peoplewerx.com
name: Knowledgepreneur
title: Working Smarter - Artificial Intelligence and Productivity
