typography_spectrum: 0.9345090012066066
color:
  brandStrength: 0.10871128807775676
  lightness: 0.18324361904524267
  saturation: 0.8975657974369824
  rhythmicContrast: 0.9218097829725593
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.6599569136742502
author:
  name: Mark Palmer
  email: mpalmer@peoplewerx.com
  url: www.peoplewerx.com
name: Knowledgepreneur
navigation:
  - name: About Mark Palmer
    url: 'https://www.linkedin.com/in/markpalmer'
    type: external
title: Working Smarter - Artificial Intelligence and Productivity
